###
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
    "nameProduct": "balon de futbol",
    "priceProduct": 70,
    "desc": "balon de futbol"
}

###
GET http://localhost:9000/api/products HTTP/1.1

###
GET http://localhost:9000/api/products/655d55db0d2201d6279aa6ac HTTP/1.1

###

PUT http://localhost:9000/api/products/655d55db0d2201d6279aa6ac HTTP/1.1
Content-Type: application/json

{
    "nameProduct": "guantes de arquero",
    "priceProduct": 100,
    "desc": "guantes para tapar"
}

###
DELETE http://localhost:9000/api/products/655d7190d88565c9848839d8 HTTP/1.1
